import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from 'next-auth/react';
import { Session } from "next-auth";
import SessionProviderWrapper from "./providers/session-provider";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
  session: Session | null | undefined;
}

const RootLayout = ({ children, session } : Props) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <SessionProviderWrapper session={session}> */}
          {children}
        {/* </SessionProviderWrapper> */}
      </body>
    </html>
  );
};

export default RootLayout;
